apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: inerente/mariadb:v1v
        resources:
          limits:
            memory: "3072Mi"
            cpu: "2000m"
        ports:
          - containerPort: 3306
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: 
          - name: MARIADB_DATABASE
            value: 
          - name: DB_HOST
            value: mariadb-service

---

apiVersion: v1 
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
